# Generated by Django 4.2.1 on 2023-05-25 21:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day', models.IntegerField()),
                ('aircraft', models.IntegerField()),
                ('helicopter', models.IntegerField()),
                ('tank', models.IntegerField()),
                ('apc', models.IntegerField()),
                ('field_artillery', models.IntegerField()),
                ('mrl', models.IntegerField()),
                ('military_auto', models.IntegerField()),
                ('fuel_tank', models.IntegerField()),
                ('drone', models.IntegerField()),
                ('naval_ship', models.IntegerField()),
                ('anti_aircraft_warfare', models.IntegerField()),
                ('special_equipment', models.IntegerField()),
                ('mobile_srbm_system', models.IntegerField()),
                ('greatest_losses_direction', models.TextField()),
                ('vehicles_and_fuel_tanks', models.IntegerField()),
                ('cruise_missiles', models.IntegerField()),
                ('total_air_units', models.IntegerField()),
                ('total_naval_units', models.IntegerField()),
                ('total_ground_units', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('aircraft', models.FloatField()),
                ('aircraft_lower', models.FloatField()),
                ('aircraft_upper', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='EventsMap',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('type', models.TextField()),
                ('location', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('notes', models.TextField()),
                ('fatalities', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EventsMap2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('type', models.TextField()),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Kills',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('day', models.IntegerField()),
                ('losses', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TestModel3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('tanks', models.IntegerField()),
                ('fuel', models.IntegerField()),
            ],
        ),
    ]
