# Generated by Django 4.2.1 on 2023-05-19 09:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('war_info_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsMap',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('type', models.TextField()),
                ('location', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('notes', models.TextField()),
                ('fatalities', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Kills',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('day', models.IntegerField()),
                ('losses', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TestModel3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('tanks', models.IntegerField()),
                ('fuel', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
