# Generated by Django 4.2.1 on 2023-05-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('war_info_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
