# Generated by Django 4.2.1 on 2023-05-11 11:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('war_info_app', '0002_testmodel2_delete_testmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('tanks', models.IntegerField()),
                ('fuel', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='TestModel2',
        ),
    ]
