# Generated by Django 4.2.1 on 2023-05-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('war_info_app', '0002_eventsmap_kills_testmodel3_delete_testmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day', models.IntegerField()),
                ('aircraft', models.IntegerField()),
                ('helicopter', models.IntegerField()),
                ('tank', models.IntegerField()),
                ('APC', models.IntegerField()),
                ('field_artillery', models.IntegerField()),
                ('MRL', models.IntegerField()),
                ('military_auto', models.IntegerField()),
                ('fuel_tank', models.IntegerField()),
                ('drone', models.IntegerField()),
                ('naval_ship', models.IntegerField()),
                ('anti_aircraft_warfare', models.IntegerField()),
                ('special_equipment', models.IntegerField()),
                ('mobile_SRBM_system', models.IntegerField()),
                ('greatest_losses_direction', models.IntegerField()),
                ('vehicles_and_fuel_tanks', models.IntegerField()),
                ('cruise_missiles', models.IntegerField()),
                ('Total_Air_Units', models.IntegerField()),
                ('Total_Naval_Units', models.IntegerField()),
                ('Total_Ground_Units', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('aircraft', models.IntegerField()),
                ('aircraft_lower', models.IntegerField()),
                ('aircraft_upper', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EventsMap2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('type', models.TextField()),
            ],
        ),
    ]
