# Generated by Django 4.2.1 on 2023-05-16 16:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('war_info_app', '0003_testmodel3_delete_testmodel2'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsMap',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('type', models.TextField()),
                ('location', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('notes', models.TextField()),
                ('fatalities', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Kills',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('day', models.IntegerField()),
                ('losses', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='testmodel3',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
