# Generated by Django 4.2.1 on 2023-05-25 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('war_info_app', '0003_equipment_equipmentprediction_eventsmap2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='APC',
            new_name='apc',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='MRL',
            new_name='mobile_srbm_system',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='Total_Air_Units',
            new_name='mrl',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='Total_Ground_Units',
            new_name='total_air_units',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='Total_Naval_Units',
            new_name='total_ground_units',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='mobile_SRBM_system',
            new_name='total_naval_units',
        ),
    ]
