# Generated by Django 4.2.1 on 2023-05-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('war_info_app', '0004_rename_apc_equipment_apc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='greatest_losses_direction',
            field=models.TextField(),
        ),
    ]
